#include "frugal/grubcfg.h"
#include "frugal/util.h"

#include <stdlib.h>
#include <string.h>

/* The static master grub.cfg. Recognizes things by identity (search --file),
 * never by disk order, so it is correct no matter how many disks are attached. */
static const char MASTER[] =
"# ===== ISO2Drive master grub.cfg -- generated, do not edit =====\n"
"insmod part_gpt ; insmod part_msdos\n"
"insmod fat ; insmod ntfs ; insmod ext2\n"
"insmod search_fs_file ; insmod chain ; insmod loopback\n"
"\n"
"set timeout=10\n"
"set default=0\n"
"\n"
"# Locate this tool's ISO store by its marker (identity, not disk order).\n"
"search --no-floppy --set=i2droot --file /iso2drive/.iso2drive-store\n"
"\n"
"# --- Windows: auto-detect, correct method for whichever firmware booted us ---\n"
"if [ \"$grub_platform\" = \"efi\" ]; then\n"
"    menuentry \"Windows Boot Manager\" --class windows {\n"
"        search --no-floppy --set=root --file /EFI/Microsoft/Boot/bootmgfw.efi\n"
"        chainloader /EFI/Microsoft/Boot/bootmgfw.efi\n"
"    }\n"
"else\n"
"    menuentry \"Windows\" --class windows {\n"
"        insmod ntfs\n"
"        search --no-floppy --set=root --file /bootmgr\n"
"        chainloader +1\n"
"    }\n"
"fi\n"
"\n"
"# --- Linux frugal entries generated by ISO2Drive ---\n"
"if [ -n \"$i2droot\" ]; then\n"
"    for entry in ($i2droot)/iso2drive/entries.d/*.cfg; do\n"
"        if [ -e \"$entry\" ]; then source \"$entry\"; fi\n"
"    done\n"
"fi\n";

int grubcfg_write_master(const char *out_path) {
    return write_file(out_path, MASTER);
}

int grubcfg_write_entry(const char *entries_dir, const char *slug, const char *title,
                        const char *iso_grub_path, const distro_profile_t *prof,
                        bool persist) {
    const char *cls = (prof && prof->grub_class) ? prof->grub_class : "linux";
    char *entry = NULL;

    if (persist && prof && prof->persist_param && prof->kernel && prof->initrd && prof->cmdline_fmt) {
        /* Persistence needs our kernel arg, so boot directly (not via the ISO's
         * loopback.cfg, which we cannot pass parameters to). */
        char *cmd = str_format(prof->cmdline_fmt, iso_grub_path);
        char *pcmd = cmd ? str_format("%s %s", cmd, prof->persist_param) : NULL;
        free(cmd);
        if (!pcmd) return -1;
        entry = str_format(
            "menuentry \"%s (persistent)\" --class %s {\n"
            "    search --no-floppy --set=root --file /iso2drive/.iso2drive-store\n"
            "    set iso=\"%s\"\n"
            "    loopback loop \"$iso\"\n"
            "    linux  (loop)%s %s\n"
            "    initrd (loop)%s\n"
            "}\n",
            title, cls, iso_grub_path, prof->kernel, pcmd, prof->initrd);
        free(pcmd);
    } else {
        char *fallback;
        if (prof && prof->kernel && prof->initrd && prof->cmdline_fmt) {
            char *cmd = str_format(prof->cmdline_fmt, iso_grub_path);
            if (!cmd) return -1;
            fallback = str_format(
                "        linux  (loop)%s %s\n"
                "        initrd (loop)%s\n",
                prof->kernel, cmd, prof->initrd);
            free(cmd);
        } else {
            fallback = xstrdup(
                "        echo \"This ISO has no embedded loopback.cfg; cannot boot it generically.\"\n"
                "        sleep 5\n");
        }
        if (!fallback) return -1;
        entry = str_format(
            "menuentry \"%s\" --class %s {\n"
            "    search --no-floppy --set=root --file /iso2drive/.iso2drive-store\n"
            "    set iso=\"%s\"\n"
            "    loopback loop \"$iso\"\n"
            "    if [ -e (loop)/boot/grub/loopback.cfg ]; then\n"
            "        export iso ; set root=(loop)\n"
            "        configfile (loop)/boot/grub/loopback.cfg\n"
            "    else\n"
            "%s"
            "    fi\n"
            "}\n",
            title, cls, iso_grub_path, fallback);
        free(fallback);
    }
    if (!entry) return -1;

    char *path = str_format("%s/%s.cfg", entries_dir, slug);
    if (!path) { free(entry); return -1; }
    int rc = write_file(path, entry);
    free(path);
    free(entry);
    return rc;
}
